image: openjdk:latest

stages:
    - test
    - release

test:
    stage: test
    script:
        - env
        - chmod u+x ./runTests
        - chmod u+x ./compile
        - chmod u+x ./cleanAll
        - sh ./runTests

        # Display total line coverage
        - apt install bc
        - total_lines=$(xmllint --xpath 'string(//report/counter[@type="LINE"]/@missed + //report/counter[@type="LINE"]/@covered)' report.xml)
        - covered_lines=$(xmllint --xpath 'string(//report/counter[@type="LINE"]/@covered)' report.xml)
        - coverage=$(echo "scale=2; $covered_lines/$total_lines*100" | bc)
        - "echo \"Total Line Coverage: $coverage%\""
    artifacts:
        reports:
            coverage_report:
                coverage_format: jacoco
                path: report.xml

livrable:
    image: alpine:latest
    stage: release
    script:
        - mkdir bin
        - mkdir docs
        - tar -czvf A4.COLOMER.COURBET.FRANCO.HUET.TRONET.logiciel.etapeX.tar.gz ./
    artifacts:
        name: livrable
        paths:
            - "*.tar.gz"
    only:
        - main

pages:
    stage: release
    script:
        - chmod u+x ./genDoc
        - ./genDoc
        - mv docs public
    artifacts:
        paths:
            - public
    only:
        - main
