image: openjdk:24-ea-16-jdk-slim-bullseye

stages:
    - test
    - release

test:
    stage: test
    image: openjdk:latest
    script:
        - env
        - chmod u+x ./runTests
        - chmod u+x ./compile
        - chmod u+x ./cleanAll
        - ./compile
        - ./runTests | tee test_output.txt

        # Display total line coverage
        - total_lines=$(xmllint --xpath 'string(//report/counter[@type="LINE"]/@missed + //report/counter[@type="LINE"]/@covered)' report.xml)
        - covered_lines=$(xmllint --xpath 'string(//report/counter[@type="LINE"]/@covered)' report.xml)
        - coverage=$(awk "BEGIN {print ($covered_lines/$total_lines)*100}")
        - 'echo "Total Line Coverage: $coverage%"'

        # Vérifier la sortie pour détecter des échecs
        - grep -q "FAILURES!!!" test_output.txt && exit 1 || echo "All tests passed"
    coverage: '/Total Line Coverage: \d+(?:\.\d+)?%/'
    artifacts:
        reports:
            coverage_report:
                coverage_format: jacoco
                path: report.xml

test-scripts:
    stage: test
    script:
        - chmod u+x ./runTests
        - chmod u+x ./compile
        - chmod u+x ./simulateur
        - chmod u+x ./cleanAll
        - chmod u+x ./genDoc
        - ./compile
        # Logique
        - ./simulateur
        - ./simulateur -mess 100000
        # Analogique
        - ./simulateur -mess 100000 -nbEch 100 -seed 1234
        - ./genDoc
        - ./cleanAll

livrable:
    image: alpine:latest
    stage: release
    script:
        - mkdir bin
        - mkdir docs
        - rm -fr .git/
        - tar -czvf A4.COLOMER.COURBET.FRANCO.HUET.TRONET.logiciel.etapeX.tar.gz ./
    artifacts:
        name: livrable
        paths:
            - "*.tar.gz"
    only:
        - main

pages:
    stage: release
    script:
        - chmod u+x ./genDoc
        - ./genDoc
        - mv docs public
    artifacts:
        paths:
            - public
    only:
        - main
