image: openjdk:latest

stages:
    - test
    - release

test:
    stage: test
    script:
        - env
        - chmod u+x ./runTests
        - chmod u+x ./compile
        - chmod u+x ./cleanAll
        - sh ./runTests

        # Display total line coverage
        - total_lines=$(xmllint --xpath 'string(//report/counter[@type="LINE"]/@missed + //report/counter[@type="LINE"]/@covered)' report.xml)
        - covered_lines=$(xmllint --xpath 'string(//report/counter[@type="LINE"]/@covered)' report.xml)
        - coverage=$(awk "BEGIN {print ($covered_lines/$total_lines)*100}")
        - 'echo "Total Line Coverage: $coverage%"'
    coverage: '/Total Line Coverage: \d+(?:\.\d+)?%/'
    artifacts:
        reports:
            coverage_report:
                coverage_format: jacoco
                path: report.xml

livrable:
    image: alpine:latest
    stage: release
    script:
        - mkdir bin
        - mkdir docs
        - tar -czvf A4.COLOMER.COURBET.FRANCO.HUET.TRONET.logiciel.etapeX.tar.gz ./
    artifacts:
        name: livrable
        paths:
            - "*.tar.gz"
    only:
        - main

pages:
    stage: release
    image: openjdk:24-ea-16-jdk-slim-bullseye
    script:
        - chmod u+x ./genDoc
        - ./genDoc
        - mv docs public
    artifacts:
        paths:
            - public
    only:
        - main
