#!/bin/bash

if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then
    # Système Windows (Git Bash ou Cygwin)
    SOURCES="src;tests"
else
    # Autre système (Linux, macOS, etc.)
    SOURCES="src:tests"
fi

javac -d bin -cp "lib/*" -sourcepath $SOURCES src/simulateur/Simulateur.java tests/simulateur/AllTests.java
echo "Compilation terminée."
