#!/bin/bash
echo "Génération de la javadoc..."
javadoc -cp lib/*:bin/:. -d docs $(find src -name "*.java")
code=$?;
if [ "$code" != "0" ]; then
    echo "Erreur de génération de la documentation. code : $code";
    exit -1;
fi
echo "Javadoc générée."