#!/bin/bash

if [ "$OSTYPE" == "msys" ] || [ "$OSTYPE" == "cygwin" ]; then
    # Système Windows (Git Bash ou Cygwin)
    SOURCES="bin;lib/*"
else
    # Autre système (Linux, macOS, etc.)
    SOURCES="bin:lib/*"
fi

java -javaagent:lib/jacocoagent.jar=destfile=jacoco.exec -cp $SOURCES org.junit.runner.JUnitCore simulateur.AllTests
code=$?
if [ $code -ne 0 ]; then
    echo "Erreur d'exécution des tests. code : $code"
    exit -1
fi
java -jar lib/jacococli.jar report jacoco.exec --classfiles bin --sourcefiles src --xml report.xml
code=$?
if [ $code -ne 0 ]; then
    echo "Erreur de génération du coverage. code : $code"
    exit -1
fi

echo "Tests terminés."