#!/bin/bash
./compile

if [ "$OSTYPE" == "msys" ] || [ "$OSTYPE" == "cygwin" ]; then
    # Système Windows (Git Bash ou Cygwin)
    SOURCES="bin;lib/*"
else
    # Autre système (Linux, macOS, etc.)
    SOURCES="bin:lib/*"
fi

java -javaagent:lib/jacocoagent.jar=destfile=jacoco.exec -cp $SOURCES org.junit.runner.JUnitCore simulateur.AllTests
java -jar lib/jacococli.jar report jacoco.exec --classfiles bin --sourcefiles src --xml report.xml

echo "Tests terminés."