#!/bin/sh
./compile

if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then
    # Système Windows (Git Bash ou Cygwin)
    SOURCES="bin;lib/*"
else
    # Autre système (Linux, macOS, etc.)
    SOURCES="bin:lib/*"
fi

java -cp $SOURCES org.junit.runner.JUnitCore simulateur.AllTests
